### ISSUE TITLE
Need Movie covers and descriptions

### ISSUE THREAD

**Issue by melchin** [melchin/project#32]
At least 20.

**Comment by 8BitBadass** [comment]
how about 20 funny pics with funny titles about the pic?

**Comment by 8BitBadass** [comment]
the more i think about this the worse it sounds. Could better spend our time since we already have to write 20 short descriptions in the table and then 20 longer ones with all the same info in a pop-up. Should do 20 short ones for the table and pics but the pop-up really is irrelevant. Will add double click to add to order at least and will add table info.

**Comment by 8BitBadass** [comment]
mis close
